---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: elb-controller
  namespace: flux-system
spec:
  interval: 30m
  url: https://aws.github.io/eks-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
spec:
  interval: 60m
  releaseName: aws-load-balancer-controller
  targetNamespace: kube-system
  chart:
    spec:
      chart: aws-load-balancer-controller
      version: "1.4.0"
      sourceRef:
        kind: HelmRepository
        name: elb-controller
        namespace: flux-system
  values:
    clusterName: new-env
    replicaCount: 1
  # valuesFrom:
  # - configMapKeyRef:
  #     name: cluster-name
  #     namespace: flux-system
  #     key: management-cluster-name
  #     optional: false